dependencies:
  - name: binderhub
    # NOTE: when binderhub version is upgraded, upgrade chart version too (Chart.yaml)
    version: 0.2.0-n919.he87e25a
    repository: https://jupyterhub.github.io/helm-chart
