binderhub:
  resources:
    requests:
      cpu: 0
      memory: 0

  config:
    BinderHub:
      debug: true
      hub_url: http://127.0.0.1:31123
      # use only local docker images
      use_registry: false

  extraEnv:
    - name: PROJECTS_LIMIT_PER_USER
      value: "2"

  service:
    type: NodePort
    nodePort: 31124

  imageCleaner:
    enabled: false

  jupyterhub:
    debug:
      enabled: true
    hub:
      services:
        binder:
          url: http://127.0.0.1:31124
          oauth_redirect_uri: "http://127.0.0.1:31123/services/binder/oauth_callback"
          oauth_client_id: "binder-oauth-client-dev"
      resources:
        requests:
          cpu: 0
          memory: 0
      config:
        Authenticator:
          admin_users: ["admin"]

    proxy:
      https:
        enabled: false
      service:
        type: NodePort
        nodePorts:
          http: 31123
      chp:
        resources:
          requests:
            memory: 0
            cpu: 0

    singleuser:
      defaultUrl: "/lab"
      cpu:
        guarantee: 0
      memory:
        guarantee: 0

    scheduling:
      userScheduler:
        enabled: false
      podPriority:
        enabled: false
      userPlaceholder:
        enabled: false
